name: CPP Library Verify & Validation

# Need to update this for actual migration.
trigger: none

pr:
  - '*'

resources:
  repositories:
    - repository: travisSettings
      type: github
      name: hmcts/cjs-travis-settings
      endpoint: 'hmcts'
      ref: 'master'

pool:
  name: 'MDV-ADO-AGENT-AKS-01'
  demands:
    - identifier -equals centos8-j17

variables:
  sonarqubeProject: 'uk.gov.moj.platform.libraries:cjs-framework-libraries'

stages:
  - stage: BuildAndPublish
    jobs:
      - job: BuildAndPublish
        variables:
          JAVA_TOOL_OPTIONS: '-Dhttps.protocols=TLSv1.2,TLSv1,TLSv1.1'
          PGPORT: 5432
        steps:
          - checkout: self
          - checkout: travisSettings
            path: $(Agent.RootDirectory)/target/travis-settings
            fetchDepth: 3
          # TODO: Setup PGSQL databases
          - task: bash@3
            displayName: 'Create Postgres Databases'
            inputs:
              failOnStderr: false
              targetType: 'inline'
              script: |
                #!/bin/bash
                echo ToDo
          - task: bash@3
            displayName: 'Pre-Install'
            inputs:
              failOnStderr: false
              targetType: 'inline'
              script: |
                #!/bin/bash
                # Symlink cloned travis settings to relevant paths
                echo pwd: $(pwd)
                echo Agentdir: $(Agent.RootDirectory)
                echo Homedir: $(Agent.HomeDirectory)
                ls -al
                mkdir -p $(Agent.HomeDirectory)/.m2/
                ln -sfT $(Agent.RootDirectory)/target/travis-settings/settings.xml $(Agent.HomeDirectory)/.m2/settings.xml
                ln -sfT $(Agent.RootDirectory)/target/travis-settings/mvnw mvnw
                ln -sft $(Agent.RootDirectory) $(Agent.RootDirectory)/target/travis-settings/.mvn
          - task: bash@3
            displayName: 'Install'
            inputs:
              targetType: 'filePath'
              filePath: '$(Agent.RootDirectory)/target/travis-settings/java/install.sh'
              arguments: '-e -DexcludeGroupIds=uk.gov.justice.service,uk.gov.justice.services'
          - task: bash@3
            displayName: 'Script'
            inputs:
              targetType: 'filePath'
              filePath: '$(Agent.RootDirectory)/target/travis-settings/java/script-install.sh'
              arguments: 'coveralls:report sonar:sonar'
          - task: bash@3
            displayName: 'After Success'
            inputs:
              targetType: 'filePath'
              filePath: '$(Agent.RootDirectory)/target/travis-settings/java/after_success.sh'